"""
Example gain plugin for Chameleon, generated by
``PluginManager.create_plugin_template`` and kept in ``plugins/`` (the
default discovery directory) so a repo checkout always exercises the
load path end to end. For richer reference examples see ``demo_plugins/``.
"""

from typing import List, Dict, Any
from plugin_system import AudioEffectPlugin, PluginMetadata

class MyCustomEffectPlugin(AudioEffectPlugin):
    """Minimal gain effect -- multiplies each sample by ``gain``."""

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name="MyCustomEffect",
            version="1.0.0",
            author="Chameleon",
            description="Example gain effect (template-generated). "
                        "Multiplies samples by the 'gain' parameter.",
            category="effect",
            tags=["effect", "audio", "example"],
            parameters={
                "gain": {
                    "type": "float",
                    "default": 1.0,
                    "min": 0.0,
                    "max": 2.0,
                    "description": "Gain level"
                }
            }
        )

    def initialize(self, config: Dict[str, Any]) -> bool:
        self.logger.info(f"Initializing {self.get_metadata().name} plugin")
        return True

    def cleanup(self):
        self.logger.info(f"Cleaning up {self.get_metadata().name} plugin")

    def process_audio(self, audio_data: List[float], sample_rate: int, **params) -> List[float]:
        gain = params.get('gain', 1.0)
        return [sample * gain for sample in audio_data]

# Plugin entry point
def create_plugin():
    return MyCustomEffectPlugin()
